### ISSUE TITLE
E410: Invalid :syntax subcommand: iskeyword

### ISSUE THREAD

**Issue by formix** [lifepillar/pgsql.vim#10]
cloned the latest version as described in the README.md file, using pathogen. When opening a **.pgsql** file, the E410 error message shows up for `~/.vim/bundle/pgsql.vim/syntax/pgsql.vim` line 16.

Content of line 16: `syn iskeyword @,48-57,192-255,_`

Given the default keyword charactrs in VIM (see _:help iskeyword_), the line 16 should be replaced by:

Line 16 fix: `setlocal iskeyword+=192-255`

I don't know enough in VIM syntax definition things and how this project works with src, compilation and all to actually do a pull request so I leave it to somebody knowledgeable to fix the issue in the source code. I applied the fix in my own bundle directly in the syntax file.

Hope it helps!

**Comment by lifepillar** [comment]
Which Vim version are you using? `syn iskeyword` is the correct way to set keyword characters in syntax files: see `:help syn-iskeyword`.

**Comment by mjf** [comment]
The very same issue...

---
VIM - Vi IMproved 7.4
---

(don't laught) :grin: and, of course

---
E149: Sorry, no help for syn-iskeyword
---

(there is an entry in help for `:help iskeyword` only)

**Comment by lifepillar** [comment]
`syn iskeyword` was added in 7.4.1142. I may add a fallback for older versions.

**Comment by lifepillar** [comment]
This should be fixed in the current master. Feel free to reopen if necessary.
