### ISSUE TITLE
begin indented from declare in pgplsql mode

### ISSUE THREAD

**Issue by hrbigelow** [lifepillar/pgsql.vim#11]
Hi,

I have valid (compiles in PostgreSQL 11.3) function, but the part:

...
language pgplsql as
$$
declare
  _some_var integer;
  begin

I notice that the 'begin' is automatically indented from the 'declare', which shouldn't happen.  Would you have any advice?

Thanks very much!

Henry

**Comment by lifepillar** [comment]
That is something that must be fixed in `indent/pgsql.vim`. That file is copied almost verbatim from Vim's SQL indentation script, with minor modifications by myself. I will take a look.

**Comment by hrbigelow** [comment]
Great!  Thanks so much for your great work.  I look forward to hearing back.

Best,

Henry

**Comment by lifepillar** [comment]
This should be fixed in the current master.

**Comment by hrbigelow** [comment]
Hi lifepillar,

Thanks so much!  Just tested it and it works like a charm!
