### ISSUE TITLE
timestamp with time zone highlighted oddly

### ISSUE THREAD

**Issue by dhduvall** [lifepillar/pgsql.vim#13]
If I create a table with a column of type `timestamp with time zone`, the `with` is highlighted as if it were the statement starting a CTE, not part of the type name:
```
CREATE TABLE IF NOT EXISTS my_table (
    ts          timestamp with time zone NOT NULL DEFAULT now()
);
```

**Comment by lifepillar** [comment]
This should be fixed in the current master. Keywords like `with`, having different meanings in different contexts, are a bit tricky. Should highlighting still be wrong, feel free to reopen this issue.
