### ISSUE TITLE
Add $function$ as pl/pgsql body delimiter?

### ISSUE THREAD

**Issue by erictallman** [lifepillar/pgsql.vim#14]
When working on functions extracted from the DB using pg_get_functiondef, their bodies are delimited with `$function$`. Would it be possible to have this added as a default pl/pgsql delimiter?

**Comment by lifepillar** [comment]
I think so. I'll do it when I find the time to update the plugin for PostgreSQL 12.1.

**Comment by lifepillar** [comment]
This should be fixed in the current master.
