### ISSUE TITLE
CREATE OR ETC isn't correctly highlighted?

### ISSUE THREAD

**Issue by oblitum** [lifepillar/pgsql.vim#15]
![18:23:33_26-07-2020](https://user-images.githubusercontent.com/1269815/88489836-5a348e00-cf6d-11ea-9b85-1cf543f71580.png)

As can be seen in the above screenshot, it is not looking as the images from README.

**Comment by lifepillar** [comment]
It may depend on the color scheme.  Have you tried with a different one?

**Comment by lifepillar** [comment]
Ah no, that does not depend on the color scheme. I have made some changes along the way. But I think I can restore the syntax coloring like it looks in the Readme's images, if you prefer it that way.

**Comment by oblitum** [comment]
Personally I do prefer that, because it feels weird to have "CREATE" in one color and "OR REPLACE" in a another. Maybe "FUNCTION"/"VIEW" could  be fine in different color, but not "OR REPLACE", as it's part of the same logical thing.
