### ISSUE TITLE
RFE: support folding

### ISSUE THREAD

**Issue by mgedmin** [lifepillar/pgsql.vim#18]
I noticed that vim's standard SQL syntax plugin supported folding (via foldmethod=syntax), but it was folding my PostgreSQL statements incorrectly.  I googled for a syntax plugin that supports PostgreSQL and found this repo, but it looks like it doesn't support folding at all?

I will try to create a PR.

**Comment by lifepillar** [comment]
Closing this, as I've merge your PR solving it.
