### ISSUE TITLE
Fold functions only

### ISSUE THREAD

**Issue by zdm** [lifepillar/pgsql.vim#20]
Hi.
I want to add option that will allow to fold functions only.
If you will accept it - I can create pull request.

**Comment by lifepillar** [comment]
Sure, pull requests are welcome! Even better if you can update `src/pgsql.vim` instead of the generated syntax file. If you cannot build from source, work on the syntax file, but then copy/paste your addition into `src/pgsql.vim` (see the section after `select 'Generating syntax file...';`).

**Comment by zdm** [comment]
PR ready, check it. pls.

**Comment by lifepillar** [comment]
Merged, finally!
