### ISSUE TITLE
Syntax highlighting for PL/perl not working

### ISSUE THREAD

**Issue by rabbiveesh** [lifepillar/pgsql.vim#21]
Hi, I'm using vim 8.1.2269 (the one that comes with ubuntu 20.04 in the vim-nox package).

I have the following lines in my vimrc
```
let g:sql_type_default = 'pgsql'
let g:pgsql_pl = ['perl']
```

Yet when I have a function delimited with `$perl$`, it highlights as a multi-line string rather than perl code.
Here's what I get
![Screenshot from 2021-01-13 15-58-28](https://user-images.githubusercontent.com/23664554/104462010-b68d7780-55b8-11eb-91e8-6410d0449316.png)

**Comment by lifepillar** [comment]
It is working as expected for me. Are you using the current master of this plugin? If not, can you find which commit you are using?

**Comment by rabbiveesh** [comment]
Indeed I am using master.

**Comment by lifepillar** [comment]
OK, after double-checking this, I've realized that it's me who was using an earlier tag. This is a recent regression. I'll fix it.

**Comment by lifepillar** [comment]
This should be fixed in the current master. Feel free to reopen if necessary.
