### ISSUE TITLE
Syntax highlighting question

### ISSUE THREAD

**Issue by var211** [lifepillar/pgsql.vim#26]
Hello, help my please with small question. In older versions of this plugin all quoted names inside function body was highlighted. Now i see highlighting only outside of body. Is it some option or new behavior?

Example screenshot:
https://paste.pics/2eb27073a2c686985424ba920eb91048

**Comment by lifepillar** [comment]
I think that is a regression. Thanks for reporting. I'll fix it.

**Comment by lifepillar** [comment]
This should be fixed in the current master.
