### ISSUE TITLE
sqlFold region - problem with fragments

### ISSUE THREAD

**Issue by rabbiveesh** [lifepillar/pgsql.vim#27]
I'm having a weird issue with my code. I currently use haarg/vim-perl, with the heredoc-sql extension to highlight heredocs delimited by `SQL` as sql.

A strange thing has happened since bd0d0f274 (did a bisect), where the highlighting for SQL overruns the bounds of the heredoc. It seems that this is b/c the sqlFold group keeps going until it hits a semicolon.

In addition, somehow setting `g:pgsql_fold_functions_only` to 1 solves the  issue too.

My use case is making SQL snippets (table definitions to be used in subqueries), so i can't include a trailing semicolon (which makes the highlighting work correctly).

Not sure if this is a bug here or there. Let me know if there's anythign else I could provide that would be helpful

**Comment by lifepillar** [comment]
Thanks for reporting. Can you provide a small document to reproduce the issue?

Disabling folding would be a simple workaround. Setting `g:pgsql_fold_functions_only` works for you likely because your snippets do not contain `create function`/`procedure`.

I might add an option to disable the folding syntax groups in the plugin.

**Comment by rabbiveesh** [comment]
the following, when save in a perl `.pm` file, will show the issue when set up as described above.
```perl
use DBIx::Class::ResultDDL -V1;
view 'the_bug', <<SQL;
select id, info from table
SQL

col id => integer, auto_inc;
col info => jsonb
```

You'll see that the col lines are highlighted as SQL, rather than perl.

I'd be happy to set up a repo with the other plugin in the correct state, just not sure how to do so.

**Comment by rabbiveesh** [comment]
okay, i set up an mwe at https://github.com/rabbiveesh/pgsql-highlight-mwe. You can see the problem in action with this
```
vim -u vimrc problem.pm
```

Essentially, the `id` and `info` in the lines after the heredoc should be highlighted, rather than `integer` or `jsonb`.

**Comment by lifepillar** [comment]
I believe that the vim-perl is at fault here. That plugin should not allow contained matches to go past a match with the end pattern of a here doc. In practice, that means that they should add a `keepend` declaration to the `perlHereDocSQL` syntax group.

**Comment by rabbiveesh** [comment]
K, thanks for looking into it. I'll file this over there

**Comment by rabbiveesh** [comment]
K, i'm gonna add a patch, and closing it here.
Thanks for the help, and especially for the awesome plugin!
