### ISSUE TITLE
Builtin types are sqlKeywords

### ISSUE THREAD

**Issue by eirnym** [lifepillar/pgsql.vim#3]
Many types are marked as  sqlKeyword (some of them):
* bigint
* character varying
* TIMESTAMP WITH TIME ZONE
* TEXT
* bigserial
* serial 
* int

While custom types are marked as sqlType (some of them):
*  uuid
* json
* jsonb
…

**Comment by eirnym** [comment]
The rebuilding gives the same.

**Comment by lifepillar** [comment]
Currently, I get the built-in type names from `pg_type`:

```sql
select typname from pg_type order by typname;
```

This gives only a few names. I get most of all other keywords from `pg_get_keywords()`. The result of `pg_get_keywords()` does have a category field, but that is not useful for extracting types (e.g., both `bigint` and `coalesce` have category `C`). As far as I know, there is no way to extract all and only the “types” from the catalog. I will hard-code the type names in the generating script.

**Comment by lifepillar** [comment]
@eirnym This should be fixed in master. Let me know if there are still inconsistencies.
