### ISSUE TITLE
select distinct on and following lines doesn't work

### ISSUE THREAD

**Issue by pencilcheck** [lifepillar/pgsql.vim#30]
<img width="688" alt="Screen Shot 2022-09-05 at 1 41 21 AM" src="https://user-images.githubusercontent.com/116532/188406998-295d5dbe-aeee-4551-97e6-626b216aa2c7.png">

**Comment by pencilcheck** [comment]
nvm, I enabled tree-sitter syntax highlight and turns out it is tree-sitter interfering, closing this ticket

**Comment by lifepillar** [comment]
~~Are you the buffer is using syntax highlighting from this plugin? `distinct` and  `on` should have the same color.~~

Ok, I see that you have found the culprit.
