### ISSUE TITLE
Doesn't support #> or #>> jsonb operators

### ISSUE THREAD

**Issue by raine** [lifepillar/pgsql.vim#4]
pgsql.vim:
  
![screen shot 2018-02-13 at 17 48 56](https://user-images.githubusercontent.com/11027/36158924-2fd903a4-10e6-11e8-8b5c-b48717397718.png)

some other sql syntax highlighter:

![screen shot 2018-02-13 at 17 49 21](https://user-images.githubusercontent.com/11027/36158940-3d37229c-10e6-11e8-8189-243ceccdea0a.png)

**Comment by lifepillar** [comment]
I see. I'll fix it, likely during the weekend. Thanks for reporting!

**Comment by lifepillar** [comment]
The current master should fix this.

Highlighting operators is a little tricky: please open a new issue if this commit breaks syntax somewhere else.
