### ISSUE TITLE
Font and colorscheme

### ISSUE THREAD

**Issue by bear24rw** [lifepillar/pgsql.vim#5]
What font and colorscheme are being using in the screenshot?

**Comment by lifepillar** [comment]
[Monaco](https://en.wikipedia.org/wiki/Monaco_(typeface)) and [Gruvbox](https://github.com/morhetz/gruvbox)! In fact, currently I am using my own [fork of Gruvbox](https://github.com/lifepillar/vim-gruvbox8).
