### ISSUE TITLE
Allow escaped quotes in a string

### ISSUE THREAD

**Issue by eirnym** [lifepillar/pgsql.vim#6]
Currently part of SQL  `column = 'str\'ing' and other = 1` looks like '' there's a string `str\` and `ing` is preceeding the rest of the file which is incorrect. The same with double quotes.

**Comment by lifepillar** [comment]
The usual way to specify a quote inside a string is to use `''` [1]. Ditto for double quotes, IIRC.

But, `\'` is accepted in escape string constants. So, `E'str\'ing'` works [2]. So, perhaps it is enough to extend the syntax for escape strings?


[1] https://www.postgresql.org/docs/11/static/sql-syntax-lexical.html, 4.1.2.1.
[2] https://www.postgresql.org/docs/11/static/sql-syntax-lexical.html, 4.1.2.2.

**Comment by lifepillar** [comment]
Actually, `\'` is treated specially inside strings by older versions of PostgreSQL. In the current master, I have added a new option called `g:pgsql_backslash_quote`. If you put this in your `vimrc`:

```vim
let g:pgsql_backslash_quote = 1
```

then `\'` is treated as an escape sequence and it does not end a string. A `\'` is also treated as an escape sequence in escape string constants (i.e., strings between `E''`), no matter how the above option is set.

I have not found any reference about PostgreSQL supporting backslash escaping in double-quoted strings.

**Comment by eirnym** [comment]
I missed this option, thanks! It works for me. 

Nevertheless, there's a lot of generated SQL code and code I can't modify. Thanks for supporting this option!
